### ISSUE TITLE
package ‘ARTP2’ is not available (for R version 3.2.5 Patched)

### ISSUE THREAD

**Issue by yoyohashao** [zhangh12/ARTP3#3]
I got this when I trying to install ARTP2 using package manager in RStudio. What's the compatible R version for ARTP2? Thanks

**Comment by zhangh12** [comment]
CRAN has v0.9.32 and I can install it without problem. You may also try to download the source code and compile it by yourself. I am currently use R 3.4.x. As requested by CRAN recently, all newly uploaded package should require R (>= 3.4.0)

BTW: I am going to make another update today or tomorrow.
