### ISSUE TITLE
Can I use this for continuous trait data?

### ISSUE THREAD

**Issue by seoldh** [zhangh12/ARTP3#4]
I learned about GWAS and found a path-based test. From the manual, it seems that it can be executed only in cases and controls study. Is it applicable to continuous traits?

Thank you

**Comment by zhangh12** [comment]
you can specify argument 'family' for different traits, family='gaussian' for continuous trait and family='binomial' for binary outcome.

**Comment by seoldh** [comment]
thank you for your kind reply
